spring:
  application.name: thumb-backend
  mvc:
    servlet:
      path: /api
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lone_thumb
    username: root
    password: 123456
  data:
    # Redis 配置
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 5000
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.lone.lonethumb.controller


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

